name: biospot
description: "projeto de inovação biospot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_screenutil: ^5.9.3
  grock: ^0.5.7
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.3.1
  dropdown_search: ^5.0.6
  photo_view: ^0.15.0

  # Internal
  flutter_modular: ^6.3.4
  dio: ^5.5.0+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  intl: ^0.19.0
  easy_mask: ^2.0.1
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.4
  path_provider: ^2.1.4
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # DataBase
  path: ^1.9.0
  sqflite: ^2.3.3+1
  synchronized: ^3.1.0+1
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  assets:
    - assets/


flutter_assets_generator:
  path_ignore: [ "assets/fonts" ]
  output_dir: core/generated